SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I 
JOIN FISH_NAME_INFO AS N 
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH IN (
    SELECT MAX(LENGTH)
    FROM FISH_INFO 
    ⭐ WHERE FISH_TYPE = I.FISH_TYPE
    GROUP BY FISH_TYPE 
) 
ORDER BY I.ID;